create database pizza_sales_database;

use pizza_sales_database;

select * from pizza_sales;

-- What is the total revenue generated by each pizza category?
SELECT pizza_category, ROUND(SUM(total_price),2) AS total_revenue
FROM pizza_sales
GROUP BY pizza_category
ORDER BY total_revenue DESC;

-- Which pizza sizes generate more revenue?
SELECT pizza_size, ROUND(SUM(total_price),2) AS revenue
FROM pizza_sales
GROUP BY pizza_size
ORDER BY revenue DESC;

-- Which orders had a total value higher than the average order value?
SELECT order_id, ROUND(SUM(total_price),2) AS order_value
FROM pizza_sales
GROUP BY order_id
HAVING SUM(total_price) > (
    SELECT AVG(order_total)
    FROM (
        SELECT SUM(total_price) AS order_total
        FROM pizza_sales
        GROUP BY order_id
    ) sub
);

-- What are the top 5 pizzas by total quantity sold?
SELECT pizza_name, SUM(quantity) AS total_sold
FROM pizza_sales
GROUP BY pizza_name
ORDER BY total_sold DESC
LIMIT 5;

-- Do larger pizza sizes contribute more revenue compared to smaller sizes?
SELECT pizza_size,
    COUNT(DISTINCT order_id) AS total_orders,
    ROUND(AVG(total_price),2) AS avg_price,
    ROUND(SUM(total_price),2) AS total_revenue
FROM pizza_sales
GROUP BY pizza_size
ORDER BY total_revenue DESC;

-- What are the top 3 most ordered pizzas within each category?
WITH pizza_rank AS (
    SELECT 
        pizza_category,
        pizza_name,
        SUM(quantity) AS total_sold,
        ROW_NUMBER() OVER (
            PARTITION BY pizza_category 
            ORDER BY SUM(quantity) DESC
        ) AS pizza_rank
    FROM pizza_sales
    GROUP BY pizza_category, pizza_name
)
SELECT 
    pizza_category,
    pizza_name,
    total_sold
FROM pizza_rank
WHERE pizza_rank <= 3;

-- What is the revenue contribution by day of the week?
SELECT day_name, ROUND(SUM(total_price),2) AS total_revenue
FROM pizza_sales
GROUP BY day_name
ORDER BY total_revenue DESC;

-- At what hour of the day are the most orders placed?
SELECT HOUR(order_time) AS order_hour, COUNT(DISTINCT order_id) AS total_orders
FROM pizza_sales
GROUP BY order_hour
ORDER BY total_orders DESC;

-- Which month generated the highest revenue?
SELECT  month, ROUND(SUM(total_price),2) AS monthly_revenue
FROM pizza_sales
GROUP BY month
ORDER BY monthly_revenue DESC;
